info:
  title: Spr책kbanken Text Metadata API
  description: |
    This API provides a quick way to retrieve a list of resources (corpora, lexicons, models, analyses, and utilities)
    available at Spr책kbanken Text. It is used to display resources on [Spr책kbanken Text's
    website](https://spraakbanken.gu.se/en/resources).

    The main endpoint `/` lists metadata for all resources (unless the `resource` or `resource_type` parameter is used).
    Each resource is represented as a JSON object that adheres to the JSON schema available from the `/schema` endpoint.

    Some resources have detailed descriptions that are only displayed when using the `resource` parameter. For more
    information, please refer to the [GitHub repository](https://github.com/spraakbanken/metadata).

  contact:
    name: Spr책kbanken Text
    url: https://spraakbanken.gu.se/
    email: sb-info@svenska.gu.se
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://ws.spraakbanken.gu.se/ws/metadata/v3
    description: Production server
  - url: https://ws.spraakbanken.gu.se/ws/metadata/dev
    description: Development server

tags:
  - name: Metadata retrieval
    description: Endpoints for retrieving metadata about resources
  - name: MISC
    description: Miscellaneous endpoints
  - name: Cache management
    description: Endpoints for managing the metadata cache
  - name: Documentation
    description: Endpoints for API documentation
